config/routes.rb
Agriteca::Application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'

  get 'shop(/:category)' => 'products#index', :as => 'products'
  get 'product/:slug' => 'products#show', :as => 'product'

  post 'cart/add' => 'cart#add_item', :as => 'add_to_cart'
  post 'cart/remove/:id' => 'cart#remove_item', :as => 'remove_from_cart'
  post 'cart/update/:id/:quantity' => 'cart#update_item', :as => 'update_cart_item'
  get 'cart' => 'cart#show', :as => 'cart'

  get 'checkout' => 'orders#new', :as => 'checkout'
  post 'orders' => 'orders#create', :as => 'orders'
  get 'orders/:id' => 'orders#show', :as => 'order'
  get 'orders/:id/pay' => 'orders#pay', :as => 'pay_order' # dummy page (to be replaced by offsite payment gateway)
  get 'orders/:id/success' => 'orders#success', :as => 'order_success' # cardgate return url
  get 'orders/:id/failed' => 'orders#failed', :as => 'order_failed' # cardgate return url failed
  post 'orders/callback' => 'orders#callback', :as => 'order_callback' # cardgate control url (callback)

  get 'news/archive' => 'news#archive', :as => 'news_archive'
  get 'news/:id' => 'news#show', :as => 'news_item'

  resources :events

  get 'contact_form' => 'contacts#new', :as => 'contact_form'
  post 'contact_form' => 'contacts#submit', :as => 'submit_contact_form'

  get ':slug' => 'pages#show', :as => 'page'

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_filter :get_cart

  def add_item
    @product = Product.find params[:product_id]

    if @product
      line_item = LineItem.new product: @product, price: @product.price
      line_item.quantity = params[:quantity] || 1
      params[:options].each do |option_id, variation_id|
        option = Attribute.find(option_id)
        variation = Variation.find(variation_id)
        line_item.variations.build option: option.title, variation: variation.title
      end if params[:options]

      @cart.add line_item, line_item.price, line_item.quantity
    end
    flash[:success] = t('item_added')
    redirect_to @product
  end

  def remove_item
    cart_item = ShoppingCartItem.find params[:id]
    cart_item.delete

    redirect_to cart_path
  end

  def update_item
    cart_item = ShoppingCartItem.find params[:id]
    quantity = params[:quantity].to_i
    if quantity >= 1
      cart_item.update_quantity params[:quantity]
      cart_item.item.quantity = params[:quantity]
    else
      cart_item.delete
    end

    redirect_to cart_path
  end

  def show
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/show.html.erb
<% provide :title, t("shopping_cart") %>

<div class="row">
  <div class="col-sm-3">
    <div class="sidebar">
      <div class="block">
        <h3 class="title"><%= t("categories") %></h3>
        <ul class="menu">
          <%= product_menu(@category) %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-9">
    <h1 class="title"><%= t("shopping_cart") %></h1>
    <div id="cart">
      <% if @cart.empty? %>
        <p><%= t("empty_shopping_cart") %></p>
      <% else %>
        <table id="cart-items" class="table">
          <thead>
            <tr>
              <th><%= t("item") %></th>
              <th><%= t("price") %></th>
              <th><%= t("quantity") %></th>
              <th><%= t("subtotal") %></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @cart.shopping_cart_items.each do |cart_item| %>
              <tr>
                <td>
                  <%= cart_item.item.product.title %><br />
                  <small><%= cart_item.item.variations.map { |v| "#{v.option}: #{v.variation}"}.join(", ") %></small>
                </td>
                <td><%= number_to_currency cart_item.price, unit: "€" %></td>
                <td>
                  <%= text_field_tag :quantity, cart_item.quantity, data: {cart_item: cart_item.id}, class: "cart-item-quantity text-center" %>
                </td>
                <td><%= number_to_currency cart_item.subtotal, unit: "€" %></td>
                <td><%= link_to t("remove"), remove_from_cart_path(cart_item.id), method: :post %></td>
              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr class="active">
              <td colspan="3"></td>
              <td><%= t("subtotal") %></td>
              <td><%= number_to_currency @cart.total, unit: "€" %></td>
            </tr>
          </tfoot>
        </table>
        <div class="cart-actions text-right">
          <%= link_to t("continue_shopping"), products_path, class: "btn btn-default" %>
          <%= link_to t("checkout"), checkout_path, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>