config/routes.rb
Agriteca::Application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'

  get 'shop(/:category)' => 'products#index', :as => 'products'
  get 'product/:slug' => 'products#show', :as => 'product'

  post 'cart/add' => 'cart#add_item', :as => 'add_to_cart'
  post 'cart/remove/:id' => 'cart#remove_item', :as => 'remove_from_cart'
  post 'cart/update/:id/:quantity' => 'cart#update_item', :as => 'update_cart_item'
  get 'cart' => 'cart#show', :as => 'cart'

  get 'checkout' => 'orders#new', :as => 'checkout'
  post 'orders' => 'orders#create', :as => 'orders'
  get 'orders/:id' => 'orders#show', :as => 'order'
  get 'orders/:id/pay' => 'orders#pay', :as => 'pay_order' # dummy page (to be replaced by offsite payment gateway)
  get 'orders/:id/success' => 'orders#success', :as => 'order_success' # cardgate return url
  get 'orders/:id/failed' => 'orders#failed', :as => 'order_failed' # cardgate return url failed
  post 'orders/callback' => 'orders#callback', :as => 'order_callback' # cardgate control url (callback)

  get 'news/archive' => 'news#archive', :as => 'news_archive'
  get 'news/:id' => 'news#show', :as => 'news_item'

  resources :events

  get 'contact_form' => 'contacts#new', :as => 'contact_form'
  post 'contact_form' => 'contacts#submit', :as => 'submit_contact_form'

  get ':slug' => 'pages#show', :as => 'page'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :orders
  has_one :coupon
  has_one :commission_invoice

  scope :between, lambda { |start_time, end_time| where(date: Time.at(start_time.to_i)..Time.at(end_time.to_i)) }
  scope :ended, lambda { where 'end_date <= ?', Time.now }

  just_define_datetime_picker :date
  just_define_datetime_picker :end_date

  after_initialize :set_date

  after_create :generate_code

  validates_presence_of :user, :title, :date

  def self.generate_coupons
    # this method runs every day

    # check if there are events that have ended and that do not have a coupon yet
    events = Event.ended.where coupon: nil
    events.each do |e|
      e.generate_coupon
    end
  end

  def self.generate_commission_invoices
    # this method runs every day

    # check if there are events that have ended and that do not have a commission invoice yet
    events = Event.ended.where commission_invoice: nil
    events.each do |e|
      e.generate_commission_invoice if e.user.profile.gets_commission?
    end
  end

  def set_date
    self.date ||= Time.now
    self.end_date ||= Time.now + 1.day
  end

  def generate_code
    self.code = self.user.name.split(" ").map{|s|s.first.upcase}.join("") + '-' + SecureRandom.hex(2).upcase + '-' + self.id.to_s
    save
  end

  def generate_coupon
    # get total of all (regular) orders
    event_orders = self.orders.paid.where created_at: (self.date..self.end_date)
    event_order_total = event_orders.inject(0) { |sum,o| sum+o.subtotal }

    # generate coupon code
    code = SecureRandom.hex(8).upcase
    self.build_coupon code: code, value: event_order_total * 0.1
    save

    # check if hoster info is available
    if self.hoster_email?
      CouponMailer.new_coupon(self.coupon).deliver # mail to user
    end

  end

  def generate_commission_invoice
    event_orders = self.orders.paid.where created_at: (self.date..self.end_date)
    event_order_total = event_orders.inject(0) { |sum,o| sum+o.total_with_vat }
    self.build_commission_invoice total: event_order_total * 0.2, user: self.user, year: Date.today.year, invoice_type: 'event'
    save
    InvoiceMailer.invoice(self.commission_invoice).deliver
  end

  def ended?
    self.end_date <= Time.now
  end

  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || '',
      :start => self.date.rfc822,
      :end => self.date.rfc822,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => :show

  # before_filter :require_login, except: :show

  def index
    @events = current_user.events
    @events = current_user.events.between(params['start'], params['end']) if (params['start'] && params['end'])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  def show
    # @event = current_user.events.find(params[:id])
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  def new
    @event = current_user.events.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  def create
    @event = current_user.events.new(event_parameters)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      format.html # edit.html.erb
      format.json { render :json => @event }
    end
  end

  def update
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      if @event.update(event_parameters)
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
  def require_login
    unless user_signed_in?
      flash[:error] = t('login_required')
      redirect_to new_user_session_path
    end
  end

  def event_parameters
    params.require(:event).permit(:title, :date, :description, :location, :hoster_name, :hoster_email)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <div class="form-group row">
    <div class="col-xs-12">
      <%= f.input :title %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-xs-12">
      <%= f.input :date, input_html: {value: @event.date.to_formatted_s(:db), data: {behaviour: "datepicker", date_format: "YYYY-MM-DD HH:mm:ss"}}, as: :string %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-xs-12">
      <%= f.input :location %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-xs-6">
      <%= f.input :hoster_name %>
    </div>
    <div class="col-xs-6">
      <%= f.input :hoster_email %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-xs-12">
      <%= f.input :description %>
    </div>
  </div>
  <div class="form-actions text-right">
    <%= link_to t("back"), events_path, class: "btn btn-default" %>
    <%= f.submit t("submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% provide :title, @event.title %>

<h1 class="title"><%= t("edit_event") %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<% provide :title, t("your_events") %>

<h1 class="title"><%= t("your_events") %> <%= link_to t("new_event"), new_event_path, class: "btn btn-primary btn-sm pull-right" %></h1>
<div id="calendar"></div>

app/views/events/new.html.erb
<% provide :title, t("new_event") %>

<h1 class="title"><%= t("new_event") %></h1>

<%= render 'form' %>

app/views/events/show.html.erb
<% provide :title, @event.title %>

<h1 class="title"><%= @event.title %></h1>

<dl id="event-details">
  <dt>Date</dt><dd><%= @event.date.to_s(:long) %></dd>
  <dt>End date</dt><dd><%= @event.end_date.to_s(:long) %></dd>
  <dt>Location</dt><dd><%= @event.location %></dd>
  <dt>Hoster</dt><dd><%= mail_to @event.hoster_email, @event.hoster_name %></dd>
  <dt>Description</dt><dd><%= simple_format @event.description %></dd>
</dl>
<div id="event-code">Event code: <%= @event.code %></div>

<%= link_to t("edit"), edit_event_path(@event), class: "btn btn-default" %>
<%= link_to t("delete"), @event, class: "btn btn-default", method: :delete, data: {confirm: "Are you sure?"} %>