config/routes.rb
Agriteca::Application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'

  get 'shop(/:category)' => 'products#index', :as => 'products'
  get 'product/:slug' => 'products#show', :as => 'product'

  post 'cart/add' => 'cart#add_item', :as => 'add_to_cart'
  post 'cart/remove/:id' => 'cart#remove_item', :as => 'remove_from_cart'
  post 'cart/update/:id/:quantity' => 'cart#update_item', :as => 'update_cart_item'
  get 'cart' => 'cart#show', :as => 'cart'

  get 'checkout' => 'orders#new', :as => 'checkout'
  post 'orders' => 'orders#create', :as => 'orders'
  get 'orders/:id' => 'orders#show', :as => 'order'
  get 'orders/:id/pay' => 'orders#pay', :as => 'pay_order' # dummy page (to be replaced by offsite payment gateway)
  get 'orders/:id/success' => 'orders#success', :as => 'order_success' # cardgate return url
  get 'orders/:id/failed' => 'orders#failed', :as => 'order_failed' # cardgate return url failed
  post 'orders/callback' => 'orders#callback', :as => 'order_callback' # cardgate control url (callback)

  get 'news/archive' => 'news#archive', :as => 'news_archive'
  get 'news/:id' => 'news#show', :as => 'news_item'

  resources :events

  get 'contact_form' => 'contacts#new', :as => 'contact_form'
  post 'contact_form' => 'contacts#submit', :as => 'submit_contact_form'

  get ':slug' => 'pages#show', :as => 'page'

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :event
  belongs_to :coupon
  has_one :invoice, dependent: :destroy

  before_save :update_delivery_address
  before_save :calc_shipping_info

  enumerate :country
  enumerate :delivery_country, with: Country
  enumerate :from_country, with: Country
  enumerate :shipping_type

  scope :paid, -> { where(paid: true) }
  scope :unpaid, -> { where(paid: false) }

  # attr_reader :code

  before_create :set_reference

  validates_presence_of :first_name, :name, :email, :address1, :postal_code, :city, :country, :phone_number
  validates_presence_of :delivery_name, :delivery_address1, :delivery_postal_code, :delivery_city, :delivery_country, if: :other_delivery_address
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :vat_number, :valvat => {:allow_blank => true}
  validates :terms_of_service, acceptance: true
  # validate :validate_code

  # def validate_code
  #   if Event.find_by_code(code).nil?
  #     errors.add(:code, I18n.t('invalid_code'))
  #   end
  # end

  def code
    self.event ? self.event.code : nil
  end

  def code=(code)
    event = Event.find_by_code(code)
    self.event = event
  end

  def coupon_code
    self.coupon ? self.coupon.code : nil
  end

  def coupon_code=(coupon_code)
    coupon = Coupon.find_by_code(coupon_code)

    self.coupon = coupon if coupon && !coupon.used?
  end

  def discount
    self.coupon ? ([coupon.value, total_with_vat].min) : 0
  end

  def set_reference
    self.reference = SecureRandom.hex
  end

  def full_name
    "#{first_name} #{name}"
  end

  def full_address
    "#{address2.blank? ? address1.to_s : address1.to_s + ' ' + address2.to_s}, #{postal_code} #{city}, #{country(:name)}"
  end

  def full_delivery_address
    "#{delivery_address2.blank? ? delivery_address1.to_s : delivery_address1.to_s + ' ' + delivery_address2.to_s}, #{delivery_postal_code} #{delivery_city}, #{delivery_country(:name)}"
  end

  def subtotal
    line_items.inject(0) { |sum, i| sum += (i.price * i.quantity) }
  end

  def total_without_vat
    subtotal / (1 + vat_percentage)
  end

  def vat_percentage
    0.21
  end

  def vat
    subtotal - total_without_vat
  end

  def total_with_vat
    calc_shipping_info unless shipping_cost
    (vat_payable? ? subtotal : total_without_vat) + shipping_cost - discount
  end

  def total_in_cents
    (total_with_vat * 100).to_i
  end

  def vat_payable?
    vat_number.blank? || country == Country[:netherlands]
  end

  def weight
    line_items.inject(0) { |sum, i| sum += (i.product.weight * i.quantity) }
  end

  def ships_from_belgium
    line_items.all? { |i| i.product.ships_from_belgium }
  end

  def update_delivery_address
    unless self.other_delivery_address
      self.delivery_name = "#{self.first_name} #{self.name}"
      self.delivery_address1 = self.address1
      self.delivery_address2 = self.address2
      self.delivery_country = self.country
      self.delivery_city = self.city
      self.delivery_postal_code = self.postal_code
    end
  end

  def calc_shipping_info
    if self.delivery_country?
      # set from_country
      be = Country[:belgium]
      nl = Country[:netherlands]

      if self.delivery_country != be || !self.ships_from_belgium
        self.from_country = nl
      else
        self.from_country = be
      end

      to_country = self.country
      to_country = be if self.from_country == nl && to_country != nl

      w = self.weight

      letter = ShippingType[:letter]
      parcel = ShippingType[:parcel]

      sc = nil

      if line_items.all? { |i| i.product.shipping_type == letter }
        sc = ShippingCost.where("
          from_country = ? AND
          to_country = ? AND
          shipping_type = ? AND
          max_weight >= ?", self.from_country, to_country, letter, w).
        order(max_weight: :asc).first
      end

      if sc.nil?
        sc = ShippingCost.where("
          from_country = ? AND
          to_country = ? AND
          shipping_type = ? AND
          max_weight >= ?", self.from_country, to_country, parcel, w).
        order(max_weight: :asc).first
      end

      if sc
        # set shipping_type and shipping_cost
        self.shipping_type = sc.shipping_type
        self.shipping_cost = sc.cost
      else
        # TODO: error, no shipping cost found
        self.shipping_cost = 0
      end

    else
      # TODO: error, country must be filled in
      self.shipping_cost = 0
    end
  end

  def generate_invoice
    self.build_invoice unless self.invoice
    save
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  # cardgate settings
  @@hash_key = 'c3xkCX9h'
  @@siteid = '4952'
  @@test = false

  before_filter :get_cart, only: [:new, :create]

  def new
    if @cart.empty?
      redirect_to cart_path
    else
      @order = Order.new
      @other_delivery_address = false
    end
  end

  def create
    # event = Event.find_by_code(code)
    @other_delivery_address = params[:other_delivery_address]

    @order = Order.new(order_parameters)
    @cart.shopping_cart_items.each do |cart_item|
      line_item = cart_item.item
      @order.line_items << line_item
    end
    @order.calc_shipping_info
    if @order.save
      @cart.clear
      redirect_to pay_order_path(@order)
    else
      render "new"
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def pay
    @test = @@test ? '1' : '0'
    @siteid = @@siteid
    @order = Order.find(params[:id])
    @description = ''
    @hash = calc_hash(@order)
    @cardgate_url = 'https://gateway.cardgateplus.com/'
  end

  def success
    @order = Order.find(params[:id])
    flash[:success] = t('order_success')
    OrderMailer.order_success(@order).deliver
    redirect_to @order
  end

  def failed
    @order = Order.find(params[:id])
    flash[:error] = t('order_failed')
    redirect_to pay_order_path(@order)
  end

  def callback
    # todo: check hash
    transaction_id = params[:transaction_id]
    ref = params[:ref]
    status = params[:status].to_i
    payment_method = params[:billing_option]

    @order = Order.find_by_reference(ref)
    if @order
      unless @order.status == 200
        @order.update_attribute :status, status
        @order.update_attribute :payment_method, payment_method
        if status == 200
          @order.generate_invoice
          @order.update_attribute :paid, true
          OrderMailer.order_confirmation(@order).deliver # mail to user
          OrderMailer.order_details(@order).deliver # mail to admin
        end
      end
    end
    render text: "#{transaction_id}.#{status}"
  end

  private
  def order_parameters
    params.require(:order).permit(:first_name, :name, :email, :address1, :address2, :country, :city, :postal_code, :phone_number, :code, :coupon_code,
      :other_delivery_address, :delivery_name, :delivery_address1, :delivery_address2, :delivery_country, :delivery_city, :delivery_postal_code, :vat_number, :terms_of_service)
  end

  def calc_hash(order)
    elements = [@@siteid, order.total_in_cents, order.reference, @@hash_key]
    elements.unshift 'TEST' if @@test
    Digest::MD5.hexdigest(elements.join)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
<div id="order-details" class="row">
  <div class="col-sm-4">
    <h2 class="title"><%= t("your_information") %></h2>
    <div class="product-options">
      <dl>
        <dt><%= t("name") %></dt>
        <dd><%= order.first_name %> <%= order.name %></dd>

        <dt><%= t("email") %></dt>
        <dd><%= order.email %></dd>

        <% if order.vat_number? %>
          <dt><%= t("vat_number") %></dt>
          <dd><%= order.vat_number %></dd>
        <% end %>

        <dt><%= t("address") %></dt>
        <dd>
          <address>
            <%= order.address1 %><br />
            <% unless order.address2.empty? %> <%= order.address2 %><br /> <% end %>
            <%= order.postal_code %>, <%= order.city %><br />
            <%= order.country(:name) %>
          </address>
        </dd>

        <dt><%= t("delivery_address") %></dt>
        <dd>
          <address>
            <%= order.delivery_address1 %><br />
            <% unless order.delivery_address2.empty? %> <%= order.delivery_address2 %><br /> <% end %>
            <%= order.delivery_postal_code %>, <%= order.delivery_city %><br />
            <%= order.delivery_country(:name) %>
          </address>
        </dd>

        <dt><%= t("phone_number") %></dt>
        <dd><%= order.phone_number %></dd>
      </dl>
    </div>
  </div>
  <div class="col-sm-8">
    <h2 class="title"><%= t("order_summary") %></h2>
    <table id="cart-items" class="table">
      <thead>
        <tr>
          <th><%= t("item") %></th>
          <th><%= t("price") %></th>
          <th><%= t("quantity") %></th>
          <th><%= t("subtotal") %></th>
        </tr>
      </thead>
      <tbody>
        <% order.line_items.each do |item| %>
          <tr>
            <td>
              <%= item.product.title %><br />
              <small><%= item.variations.map { |v| "#{v.option}: #{v.variation}"}.join(", ") %></small>
            </td>
            <td><%= number_to_currency item.price, unit: "€" %></td>
            <td>
              <%= item.quantity %>
            </td>
            <td><%= number_to_currency item.price * item.quantity, unit: "€" %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3"><%= t("subtotal") %></td>
          <td><%= number_to_currency order.subtotal, unit: "€" %></td>
        </tr>
        <% if order.vat_payable? %>
          <tr>
            <td colspan="3"><%= t("vat_incl", percentage: number_to_percentage(order.vat_percentage * 100, precision: 0)) %></td>
            <td><%= number_to_currency order.vat, unit: "€" %></td>
          </tr>
        <% else %>
          <tr>
            <td colspan="3"><%= t("vat_free", percentage: number_to_percentage(order.vat_percentage * 100, precision: 0)) %></td>
            <td><%= number_to_currency -order.vat, unit: "€" %></td>
          </tr>
        <% end %>
        <tr>
          <td colspan="3"><%= t("shipping_cost") %></td>
          <td><%= number_to_currency order.shipping_cost, unit: "€" %></td>
        </tr>
        <% if order.discount > 0 %>
          <tr>
            <td colspan="3"><%= t("discount") %></td>
            <td><%= number_to_currency -order.discount, unit: "€" %></td>
          </tr>
        <% end %>
        <tr class="active">
          <td colspan="3"><%= t("total") %></td>
          <td><%= number_to_currency order.total_with_vat, unit: "€" %></td>
        </tr>
      </tfoot>
    </table>

  </div>
</div>

app/views/orders/new.html.erb
<% provide :title, t("checkout") %>

<div class="row">
  <div class="col-sm-6">
    <h2 class="title"><%= t("enter_your_information") %></h2>
    <%= simple_form_for @order do |f| %>
      <div class="form-group row">
        <div class="col-xs-6">
          <%= f.input :first_name, label: t('first_name'), hint: false, placeholder: false %>
        </div>
        <div class="col-xs-6">
          <%= f.input :name, label: t('last_name'), hint: false, placeholder: false %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-xs-12">
          <%= f.input :email, hint: false, placeholder: false %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-xs-12">
          <%= f.input :vat_number, label: t('vat_number'), hint: false, placeholder: false %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-xs-12">
          <%= f.input :address1, label: t('address') %>
          <%= f.input :address2, label: false %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-xs-9">
          <%= f.input :city, label: t('city') %>
        </div>
        <div class="col-xs-3">
          <%= f.input :postal_code, label: t('postal_code') %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-xs-12">
          <%= f.input :country, label: t('country'), collection: Country.to_select %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-xs-12">
          <%= f.input :phone_number, label: t('phone_number'), hint: false, placeholder: false %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-xs-12">
          <%= f.input :code, label: t('event_code') %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-xs-12">
          <%= f.input :coupon_code, label: t('hoster_coupon_code') %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-xs-12">
          <% content_for(:terms_of_service) do %>
            <%= t('accept_terms_of_service', link: link_to(t('terms_of_service'), '/algemene-voorwaarden', target: '_blank')).html_safe %>
          <% end %>
          <%= f.input :terms_of_service, as: :boolean, label: content_for(:terms_of_service), inline_label: true, hint: false, class: 'checkbox-inline' %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-xs-12">
          <%= f.input :other_delivery_address, label: t('other_delivery_address'), inline_label: true, hint: false %>
        </div>
      </div>
      <%= field_set_tag t('delivery_address'), id: 'delivery_address' do %>
        <div class="form-group row">
          <div class="col-xs-12">
            <%= f.input :delivery_name, label: t('name') %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-xs-12">
            <%= f.input :delivery_address1, label: t('address') %>
            <%= f.input :delivery_address2, label: false %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-xs-12">
            <%= f.input :delivery_country, collection: Country.to_select, label: t('country') %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-xs-9">
            <%= f.input :delivery_city, label: t('city') %>
          </div>
          <div class="col-xs-3">
            <%= f.input :delivery_postal_code, label: t('postal_code') %>
          </div>
        </div>
      <% end %>

      <div class="form-actions text-right">
        <%= f.submit t("next_step"), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-6">
    <h2 class="title"><%= t("order_summary") %></h2>
    <table id="cart-items" class="table">
      <thead>
        <tr>
          <th><%= t("item") %></th>
          <th><%= t("price") %></th>
          <th><%= t("quantity") %></th>
          <th><%= t("subtotal") %></th>
        </tr>
      </thead>
      <tbody>
        <% @cart.shopping_cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= cart_item.item.product.title %><br />
              <small><%= cart_item.item.variations.map { |v| "#{v.option}: #{v.variation}"}.join(", ") %></small>
            </td>
            <td><%= number_to_currency cart_item.price, unit: "€" %></td>
            <td>
              <%= cart_item.quantity %>
            </td>
            <td><%= number_to_currency cart_item.subtotal, unit: "€" %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr class="active">
          <td colspan="3"><%= t("subtotal") %></td>
          <td><%= number_to_currency @cart.total, unit: "€" %></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/orders/pay.html.erb
<% provide :title, "Pay now" %>

<%= render @order %>

<%= form_tag(@cardgate_url) do %>
  <%= hidden_field_tag 'test', @test %>
  <%= hidden_field_tag 'siteid', @siteid %>
  <%= hidden_field_tag 'amount', @order.total_in_cents %>
  <%= hidden_field_tag 'ref', @order.reference %>
  <%= hidden_field_tag 'description', @description %>
  <%= hidden_field_tag 'return_url', order_success_url(@order) %>
  <%= hidden_field_tag 'return_url_failed', order_failed_url(@order) %>
  <%= hidden_field_tag 'hash', @hash %>
  <%= submit_tag t('pay_now'), class: 'btn btn-primary pull-right' %>
<% end %>

app/views/orders/show.html.erb
<% provide :title, t("your_order") %>

<%= render @order %>