config/routes.rb
Agriteca::Application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'

  get 'shop(/:category)' => 'products#index', :as => 'products'
  get 'product/:slug' => 'products#show', :as => 'product'

  post 'cart/add' => 'cart#add_item', :as => 'add_to_cart'
  post 'cart/remove/:id' => 'cart#remove_item', :as => 'remove_from_cart'
  post 'cart/update/:id/:quantity' => 'cart#update_item', :as => 'update_cart_item'
  get 'cart' => 'cart#show', :as => 'cart'

  get 'checkout' => 'orders#new', :as => 'checkout'
  post 'orders' => 'orders#create', :as => 'orders'
  get 'orders/:id' => 'orders#show', :as => 'order'
  get 'orders/:id/pay' => 'orders#pay', :as => 'pay_order' # dummy page (to be replaced by offsite payment gateway)
  get 'orders/:id/success' => 'orders#success', :as => 'order_success' # cardgate return url
  get 'orders/:id/failed' => 'orders#failed', :as => 'order_failed' # cardgate return url failed
  post 'orders/callback' => 'orders#callback', :as => 'order_callback' # cardgate control url (callback)

  get 'news/archive' => 'news#archive', :as => 'news_archive'
  get 'news/:id' => 'news#show', :as => 'news_item'

  resources :events

  get 'contact_form' => 'contacts#new', :as => 'contact_form'
  post 'contact_form' => 'contacts#submit', :as => 'submit_contact_form'

  get ':slug' => 'pages#show', :as => 'page'

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :primary, -> { where(primary: true) }

  # acts_as_taggable
  enumerate :shipping_type

  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: lambda { |i| i[:file].blank? && i[:file_cache].blank? }, allow_destroy: true

  belongs_to :category, class_name: "ProductCategory", foreign_key: "category_id"

  has_and_belongs_to_many :options, class_name: "Attribute", join_table: :product_attributes
  # accepts_nested_attributes_for :options

  validates_presence_of :title, :price, :category, :weight, :shipping_type, :code
  validates_uniqueness_of :code

  scope :published, -> { where published: true }
  scope :unpublished, -> { where published: false }

  before_create :set_description

  def image
    self.images.first
  end

  def self.default_image type
    return type ? "#{type.to_s}/product-default.png" : "product-default.png"
  end

  def set_description
    self.description ||= ''
  end

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @category = nil
    if params[:category]
      begin
        @category = ProductCategory.friendly.find(params[:category])
        @products = Product.primary.where category_id: @category.subtree_ids, published: true
        @related_products = Product.where primary: false, category_id: @category.subtree_ids, published: true
      rescue ActiveRecord::RecordNotFound
        redirect_to products_url
      end
    else
      @products = Product.primary.where published: true
      @related_products = Product.where primary: false, published: true
    end
  end

  def show
    begin
      @product = Product.friendly.find(params[:slug])
      @category = @product.category
      @related_products = Product.where primary: false, category_id: @category.subtree_ids, published: true
    rescue
      redirect_to products_url
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  def product_image product, type=nil
    product.image ? product.image.file.url(type) : Product.default_image(type)
  end
end

app/views/products/_product.html.erb
<div class="product">
  <%= link_to image_tag(product_image(product, :thumb), class: "product-thumb"), product %>
  <h3 class="product-title"><%= link_to product.title, product %></h3>
</div>

app/views/products/_related.html.erb
<% unless related.empty? %>
      <div id="related">
        <h2 class="title"><%= t("related_products") %></h2>
        <% related.each_slice(3) do |slice| %>
        <div class="row">
          <% slice.each do |product| %>
            <div class="col-xs-6 col-sm-4">
              <%= render product %>
            </div>
          <% end %>
        </div>
      <% end %>
      </div>
    <% end %>

app/views/products/index.html.erb
<% provide :title, @category ? @category.title : t("all_products") %>

<div class="row">
  <div class="col-sm-3">
    <div class="sidebar">
      <div class="block">
        <h3 class="title"><%= t("categories") %></h3>
        <ul class="menu">
          <%= product_menu(@category) %>
        </ul>
      </div>
      <div class="block">
        <h3 class="title"><%= t("shopping_cart") %></h3>
        <div class="cart-body">
          <%= shopping_cart %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-9">
    <div id="products">
      <h1 class="title"><%= @category ? @category.title : t("all_products") %></h1>
      <% @products.each_slice(3) do |slice| %>
        <div class="row">
          <% slice.each do |product| %>
            <div class="col-xs-6 col-sm-4">
              <%= render product %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= render partial: "related", object: @related_products %>
  </div>
</div>

app/views/products/show.html.erb
<% provide :title, @product.title %>

<div class="row">
  <div class="col-sm-3">
    <div class="sidebar">
      <div class="block">
        <h3 class="title"><%= t("categories") %></h3>
        <ul class="menu">
          <%= product_menu(@category) %>
        </ul>
      </div>
      <div class="block">
        <h3 class="title"><%= t("shopping_cart") %></h3>
        <div class="cart-body">
          <%= shopping_cart %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-9">
    <h1 class="title"><%= @product.category.title %></h1>
    <div id="product">
      <div class="row">
        <div class="col-sm-6">
          <div class="product-images">
            <div class="main-image">
              <%= link_to image_tag(product_image(@product, :thumb)), image_path(product_image(@product)) %>
            </div>
            <div class="thumbnails">
              <% @product.images.offset(1).each do |i| %>
                <%= link_to image_tag(i.file.url(:tiny_thumb)), i.file.url %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="product-form">
            <%= form_tag add_to_cart_path, class: "form-inline" do %>
              <%= hidden_field_tag :product_id, @product.id %>
              <div class="product-title">
                <h4><%= @product.title %></h4>
              </div>
              <% unless @product.description.blank? %>
                <div class="product-description">
                  <h4><%= t("product_description") %></h3>
                  <%= @product.description.html_safe %>
                </div>
              <% end %>
              <% if @product.adult_only %>
                <div class="product-warning bg-danger"><%= t('adult_only_warning') %></div>
              <% end %>
              <div class="product-details">
                <dl>
                  <dt><%= t("category") %></dt><dd><%= link_to @product.category.title, products_path(@product.category) %></dd>
                  <dt><%= t("weight") %></dt><dd><%= @product.weight.to_s + 'gr' %></dd>
                  <dt><%= t("shipping_type") %></dt><dd><%= @product.shipping_type(:name) %></dd>
                </dl>
              </div>
              <div class="product-options">
                <% @product.options.each do |opt| %>
                  <div class="product-option">
                    <%= label_tag("options[#{opt.id}]", opt.title) %>
                    <%= select_tag("options[#{opt.id}]", options_for_select(opt.variations.map { |v| [v.title, v.id] }), prompt: t("select"), required: true, class: "form-control") %>
                  </div>
                <% end %>
              </div>
              <div class="product-price">
                <%= number_to_currency @product.price, unit: "€" %>
              </div>
              <div class="add-to-cart">
                <%= submit_tag t("add_to_cart"), class: "btn btn-primary btn-lg" %> <%= number_field_tag :quantity, 1, min: 1, required: true, class: "form-control input-lg" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: "related", object: @related_products %>
  </div>
</div>